### Available Translations
GET https://bible.helloao.org/api/available_translations.json HTTP/1.1
content-type: application/json

### Chapter List
GET https://bible.helloao.org/api/eng_asv/books.json HTTP/1.1
content-type: application/json

### Example Chapter ASV GEN 1
GET https://bible.helloao.org/api/eng_asv/GEN/1.json HTTP/1.1
content-type: application/json